name: Auto PR Test
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
        
  test:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.2.1'
      - run: bundle install
      - name: Deploy project
        run: echo "Deploying to test environment..."

  create_pull_request:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  
    - name: Create Auto PR
      uses: rematocorp/open-pull-request-action@v1
      with:
        # Github token, https://docs.github.com/en/actions/reference/authentication-in-a-workflow
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # head branch
        from-branch: test
        # base branch
        to-branch: develop
        # 
        repository-owner: sreenak
        # 
        repository: DevopsTest
          
