name: Auto Pull Request

on:
  push:
    branches:
      - develop

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create Auto PR
        uses: rematocorp/open-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          from-branch: develop
          to-branch: master
          repository-owner: sreenak
          repository: DevopsTest
